import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import Navbar from '../../../../components/Navbar';
import Estimate from '../../../../components/estimate/Estimate';
import Box from '@mui/material/Box';
import { Divider } from '@mui/material';
import '@fontsource/roboto/400.css';
import { useRouter } from 'next/router'

type Product = {
    name: string;
    price: number;
    unity?: string;
    quantity?: number;
    price_amount?: number;
}

export default function EstimatePage() {
    const router = useRouter();
    const { estimateId } = router.query;

    const [estimate, setEstimate] = useState({
        name: "",
        cnpj: "",
        statusId: 1,
        products: [],
    });

    const [busca, setBusca] = useState('');

    useEffect(() => {
        if (estimateId != undefined) {
            fetch(`/api/estimate/${estimateId}`)
                .then((response) => { return response.json(); })
                .then(data => { setEstimate(data); })
        }
    }, [estimateId])


    return (
        <>
            <Head>
                <title>EFICAZ - Orçamento</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <Estimate>
                <Box className='font-bold text-lg'>Editar Orçamento


                    <Divider className='my-2' />
                    <p> Editando o orçamento da empresa {estimate.name}</p>
                    <p> CNPJ {estimate.cnpj}</p>

                </Box>
            </Estimate>



        </>
    )
}
