import React, { useEffect, useState, useMemo, useRef } from 'react';
import Head from 'next/head'
import Navbar from '../../../components/utils/Navbar';
import Estimate from '../../../components/estimate/Estimate';
import Box from '@mui/material/Box';
import SearchField from '../../../components/estimate/SearchField';
import ExportEstimatePDF from '../../../components/estimate/ExportEstimateExcel';
import EstimateSelectedTable from '../../../components/estimate/EstimateSelectedTable';
import { Divider, Button, Container } from '@mui/material';
import '@fontsource/roboto/400.css';
import EstimateShowTable from '../../../components/estimate/EstimateShowTable';
import router from 'next/router';


export default function EstimatePage() {

  const [estimates, setEstimates] = useState([]);
  const [busca, setBusca] = useState('');

  useEffect(() => {
    
      fetch('/api/estimate/estimates')
        .then((response) => { return response.json(); })
        .then(data => { setEstimates(data); })
    
  }, [estimates])

  const filteresEstimates = useMemo(() => {
    const lowerBusca = busca.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return estimates
      .filter((estimate) => estimate.name
        .toLowerCase()
        .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        .includes(lowerBusca))
  }, [busca, estimates])

  return (
    <>
      <Head>
        <title>EFICAZ - Orçamento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />


      <Estimate>
        

        <p className='font-bold text-lg my-2'>Orçamentos</p>
        <Divider className='my-2' />
        <Box className='flex items-end'>
          <Box className='text-left w-6/12'>
            <p>Buscar</p>
            <SearchField className='w-full' onChange={(e) => setBusca(e.target.value)}></SearchField>
          </Box>
          <Box className='w-6/12 text-right'>
            <Button onClick={() => router.push(`/orcamento/create`)}>Criar orçamento</Button>
          </Box>
        </Box>
        <Divider className='my-2' />
        <EstimateShowTable data={filteresEstimates} />
      </Estimate>
    </>
  )
}
