import React, { useEffect, useState, useMemo, useRef } from 'react';
import Head from 'next/head'
import Navbar from '../../../components/Navbar';
import Estimate from '../../../components/estimate/Estimate';
import Box from '@mui/material/Box';
import SearchField from '../../../components/estimate/SearchField';
import ExportEstimatePDF from '../../../components/estimate/ExportEstimatePDF';
import EstimateSelectedTable from '../../../components/estimate/EstimateSelectedTable';
import { Divider, Button, Container } from '@mui/material';
import '@fontsource/roboto/400.css';


export default function EstimatePage() {
  const [estimates, setEstimates] = useState([]);

  useEffect(() => {
    fetch('/api/estimate/estimates')
      .then((response) => { return response.json(); })
      .then(data => { setEstimates(data); })
  }, [])

  return (
    <>
      <Head>
        <title>EFICAZ - Orçamento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />


      <Box className='font-bold text-lg'>
        <p>Orçamentos</p>

        <table>
          <tbody>
            {estimates.map((estimate, index) => (
              <tr key={index}>
                <td className="w-20" >{estimate.name}</td>
                <td className="w-20" >R$ {estimate.cnpj}</td>
           
              </tr>
            ))}
          </tbody>
        </table>

        <Divider className='my-2' />
       



      </Box>




    </>
  )
}
