import React, { useEffect, useState, useMemo } from 'react';
import Head from 'next/head'
import router from 'next/router';

import Navbar from '../../../components/utils/Navbar';
import Container from '../../../components/estimate/Container';
import SearchField from '../../../components/estimate/SearchField';
import Divider from '../../../components/utils/Divider';

import EstimateShowTable from '../../../components/estimate/EstimateShowTable';

import TemporaryTable from '../../../components/estimate/TemporaryTable';


export default function EstimatePage() {

  const [estimates, setEstimates] = useState([]);
  const [busca, setBusca] = useState('');

  useEffect(() => {

    fetch('/api/estimate/estimates')
      .then((response) => { return response.json(); })
      .then(data => { setEstimates(data); })

  }, [estimates])

  const filteresEstimates = useMemo(() => {
    const lowerBusca = busca.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return estimates
      .filter((estimate) => estimate.name
        .toLowerCase()
        .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        .includes(lowerBusca))
  }, [busca, estimates])

  return (
    <>
      <Head>
        <title>EFICAZ - Orçamento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Container>

        <p className='font-bold text-lg my-2'>Orçamentos</p>

        <Divider className='my-2' />

        <div className='flex items-end'>
          <div className='text-left w-6/12'>
            <p>Buscar</p>
            <SearchField className='w-full' onChange={(e) => setBusca(e.target.value)}></SearchField>
          </div>
          <div className='w-6/12 text-right'>
            <button type='button' className='p-3 font-bold rounded-lg bg-green-400 text-white' onClick={() => router.push(`/orcamento/create`)}>Criar orçamento</button>
          </div>
        </div>

        <Divider className='my-2' />

        <TemporaryTable data={filteresEstimates} />
        
      </Container>
    </>
  )
}
