import React, { useEffect, useState, useMemo } from 'react';
import Head from 'next/head'
import Navbar from '../../components/Navbar';
import Estimate from '../../components/estimate/Estimate';
import Box from '@mui/material/Box';
import SearchField from '../../components/estimate/SearchField';
import ExportEstimatePDF from '../../components/estimate/ExportEstimatePDF';
import EstimateSelectedTable from '../../components/estimate/EstimateSelectedTable';
import { Divider, Button } from '@mui/material';
import '@fontsource/roboto/400.css';

type Product = {
  name: string;
  unity?: string;
  quantity?: number;
  price: number;
  price_amount?: number;
}

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProducts, setSelectedProducts] = useState<Product[]>([]);
  const [totalAmount, setTotalAmount] = useState<Number>(0.0);

  const [busca, setBusca] = useState('');

  useEffect(() => {
    fetch('api/products/products')
      .then((response) => { return response.json(); })
      .then(data => { setProducts(data); })
  }, [])


  //Busca no Array
  const filteredProducts = useMemo(() => {
    const lowerBusca = busca.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return products
      .filter((product) => product.name
        .toLowerCase()
        .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
        .includes(lowerBusca))
  }, [busca, products])

  //Add a item to orçamento
  function handleSelectProduct<Product>(product) {
    setSelectedProducts((prevList) => {
      setTotalAmount(totalAmount + product.price)
      return [product, ...prevList]
    });
  }

  return (
    <>
      <Head>
        <title>EFICAZ - Orçamento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Estimate>
        <div className='font-bold text-lg'>Buscar Produtos</div>
        <SearchField onChange={(e) => setBusca(e.target.value)} />
        <Divider className='my-2' />

        <table>
        {filteredProducts.map((product) => (
          <>
            
              <tr key={product.name}>
                <td className="w-20" >{product.name}</td>
                <td className="w-20" >R$ {product.price}</td>
                <td> <Button className="text-black rounded bg-white" onClick={e => handleSelectProduct(product)}>Adicionar</Button></td>
              </tr>
            

          </>
        ))}
        </table>

        <Divider className='my-2' />

        <p className='text-lg font-bold my-2'>Produtos Selecionados</p>
        <div className="font-bold text-lg text-right my-2">
          <p>Valor Total: R$ {totalAmount}</p>
        </div>

        <EstimateSelectedTable data={selectedProducts} setSelectedProducts={setSelectedProducts} setTotalAmount={setTotalAmount} totalAmount={totalAmount} />

      </Estimate>



    </>
  )
}
